FROM library/ubuntu:16.04
RUN apt-get update
RUN apt-get install -y --no-install-recommends wget
RUN wget --quiet http://f.wsmoses.com/tapir_1.0-1_amd64.deb
RUN apt-get install -y --no-install-recommends ./tapir_1.0-1_amd64.deb
RUN rm tapir_1.0-1_amd64.deb
#RUN wget --quiet http://f.wsmoses.com/fib.c
#RUN clang fib.c -fcilkplus
#RUN ./a.out
